services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./secrets:/secrets:ro
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             gunicorn app.wsgi:application --config gunicorn.conf.py"
    environment:
      - DB_HOST=db
      - DB_NAME=orca_tracker
      - DB_USER=orca
      - DB_PASS=orca
      - OPENAI_MODEL=gpt-5-mini
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=orca
      - POSTGRES_PASSWORD=orca
      - POSTGRES_DB=orca_tracker


volumes:
  dev-db-data: