# Generated by Django 5.1.11 on 2025-08-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrcaSighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('zone', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=50)),
                ('count', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('dayOfWeek', models.PositiveIntegerField()),
                ('hour', models.PositiveIntegerField()),
                ('reportsIn5h', models.PositiveIntegerField()),
                ('reportsIn24h', models.PositiveIntegerField()),
                ('reportsInAdjacentZonesIn5h', models.PositiveIntegerField()),
                ('reportsInAdjacentPlusZonesIn5h', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RawReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeRecived', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('processed', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
            ],
        ),
    ]
