# Generated by Django 5.1.11 on 2025-08-13 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0002_rawreport_messageid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcasighting',
            name='raw_report',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sightings', to='data_pipeline.rawreport'),
            preserve_default=False,
        ),
    ]
