# Generated by Django 5.1.11 on 2025-08-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0003_orcasighting_raw_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('zoneNumber', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('boundary', models.TextField()),
                ('localities', models.TextField()),
                ('adjacentZones', models.ManyToManyField(blank=True, related_name='adjacent_to', to='data_pipeline.zone')),
                ('nextAdjacentZones', models.ManyToManyField(blank=True, related_name='next_adjacent_to', to='data_pipeline.zone')),
            ],
        ),
    ]
