# Generated by Django 5.1.11 on 2025-08-28 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0006_orcasighting_zonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcasighting',
            name='ZoneNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='data_pipeline.zone'),
        ),
    ]
