# Generated by Django 5.1.11 on 2025-09-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0007_alter_orcasighting_zonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcasighting',
            name='direction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
