# Generated by Django 5.1.11 on 2025-09-05 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0008_alter_orcasighting_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(default='xgboost_v1', help_text='Version of the prediction model used', max_length=50)),
                ('overall_confidence', models.CharField()),
                ('source_sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_batches', to='data_pipeline.orcasighting')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_bucket', models.CharField(help_text="Time bucket (e.g., '0-6h', '6-12h', '12-18h')", max_length=20)),
                ('bucket_start_hour', models.PositiveIntegerField()),
                ('bucket_end_hour', models.PositiveIntegerField()),
                ('forecast_start_time', models.DateTimeField()),
                ('forecast_end_time', models.DateTimeField()),
                ('overall_probability', models.FloatField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='data_pipeline.predictionbatch')),
            ],
            options={
                'ordering': ['bucket_start_hour'],
                'unique_together': {('batch', 'time_bucket')},
            },
        ),
        migrations.CreateModel(
            name='ZonePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100)),
                ('probability', models.FloatField()),
                ('rank', models.PositiveIntegerField()),
                ('is_top_5', models.BooleanField(default=False, help_text='Whether this zone is in the top 5 predictions')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_predictions', to='data_pipeline.predictionbucket')),
                ('zone_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='data_pipeline.zone')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('bucket', 'zone')},
            },
        ),
        migrations.DeleteModel(
            name='Prediction',
        ),
    ]
