# Generated by Django 5.1.11 on 2025-08-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawreport',
            name='messageId',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
